version: "3.3"

services:
  sematic-dev:
    image: sematic-dev:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ../:/workspace/
      - ~/.cache/bazel:/home/sematicdev/.cache/bazel
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace/
    command: /bin/bash

